postgres:
  enabled: true
  auth:
    password: &psqlPassword "psql_password"
    username: &psqlUsername "postgresql_sandbox_user"
    database: edc
  persistence:
    enabled: true

txdc:
  postgresql:
    enabled: true
    jdbcUrl: "jdbc:postgresql://txdc-postgres:5432/edc"
    username: *psqlUsername
    password: *psqlPassword
  vault:
    hashicorp:
      enabled: true
      url: "https://vault.demo.catena-x.net"
      token: ""
      paths:
        secret: "/v1/edc"
      healthCheck:
        enabled: true
        standbyOk: true

  backendService:
    httpProxyTokenReceiverUrl: "http://txdc-backend"
  serviceAccount:
    create: false

opensearch:
  enabled: true
  replicas: 1
  protocol: http
  roles:
    - master
    - ingest
    - data
  resources:
    limits:
      cpu: 300m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      # Bind to all interfaces because we don't know what
      # IP address Docker will assign to us.
      network.host: 0.0.0.0
      # Disable security
      plugins.security.disabled: true
  securityConfig:
    enabled: false
  extraInitContainers:
    # Image that performs the sysctl operation to modify Kernel settings
    # needed sometimes to avoid boot errors
    - name: sysctl
      image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
      imagePullPolicy: "IfNotPresent"
      command:
        - /bin/bash
        - -ec
        - |
          CURRENT=`sysctl -n vm.max_map_count`;
          DESIRED="262144";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w vm.max_map_count=262144;
          fi;
          CURRENT=`sysctl -n fs.file-max`;
          DESIRED="65536";
          if [ "$DESIRED" -gt "$CURRENT" ]; then
              sysctl -w fs.file-max=65536;
          fi;
      securityContext:
        runAsUser: 0
        privileged: true