backend:
  ingress:
    enabled: false
    name: "txdc-backend"
    annotations: { }
    hosts: [ ]
    tls: [ ]
  enabled: true
  service:
    frontend:
      port: 80
    backend:
      port: 8081

postgres:
  enabled: true
  auth:
    password: &psqlPassword "psql_password"
    username: &psqlUsername "postgresql_sandbox_user"
    database: edc
  persistence:
    enabled: true

txdc:
  dataplane:
    image:
      tag: 0.2.0
  controlplane:
    image:
      tag: 0.2.0
    endpoints:
      data:
        authKey: ""
  postgresql:
    enabled: true
    jdbcUrl: "jdbc:postgresql://txdc-postgres:5432/edc"
    username: *psqlUsername
    password: *psqlPassword
  vault:
    hashicorp:
      enabled: true
      url: "https://vault.demo.catena-x.net"
      token: ""
      paths:
        secret: "/v1/edc"
      healthCheck:
        enabled: true
        standbyOk: true
  daps:
    url: "https://daps1.int.demo.catena-x.net"
  backendService:
    httpProxyTokenReceiverUrl: "http://txdc-backend"
  serviceAccount:
    create: false