name: Maven Test Execution
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image pool
        run: docker build -f bpdm-pool/Dockerfile  -t maven-pool .

      - name: Build docker image gate
        run: docker build -f bpdm-gate/Dockerfile  -t maven-gate .

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      #Use Maven package cache
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #Verify with tests
      - name: Verify
        run: ./mvnw -B verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() # clause guarantees that this action always runs, even if earlier steps (e.g., the unit test step) in your workflow fail.
        with:
          files: |
            bpdm-gate/target/failsafe-reports/**/*.xml
            bpdm-orchestrator/target/failsafe-reports/**/*.xml
            bpdm-orchestrator/target/surefire-reports/**/*.xml
            bpdm-pool/target/failsafe-reports/**/*.xml
            bpdm-pool/target/surefire-reports/**/*.xml