name: Lint and Test Charts

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
             echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }} --config charts/config/chart-testing-config.yaml

      - name: Build pool image
        if: steps.list-changed.outputs.changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kind-registry:5000/pool:test
          file: ./bpdm-pool/Dockerfile

      - name: Build gate image
        if: steps.list-changed.outputs.changed == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kind-registry:5000/gate:test
          file: ./bpdm-gate/Dockerfile

      - name: Run chart-testing (install)
        run: ct install --charts charts/pool,charts/gate --config charts/config/chart-testing-config.yaml
        if: steps.list-changed.outputs.changed == 'true'