name: Lint and Test Charts

# Run chart linting and tests on each pull request
on:
  push:
    branches:
      - main
      - rc/**
    paths:
      - .github/workflows/**
      - charts/**
  pull_request:
    paths:
      - .github/workflows/**
      - charts/**
  workflow_dispatch:
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        # k8s version from 3.1 release as default
        default: 'kindest/node:v1.27.3'
        required: false
        type: string
    upgrade_from:
      description: 'chart version to upgrade from'
      # chart version from 3.1 release as default
      default: '3.1.2'
      required: false
      type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
            # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
            version: v0.20.0
            # default value for event_name != workflow_dispatch
            node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
            context: .
            file: bpdm-gate/Dockerfile
            push: true
            tags: kind-registry:5000/bpdm-gate:testing

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: bpdm-cleaning-service-dummy/Dockerfile
          push: true
          tags: kind-registry:5000/bpdm-cleaning-service-dummy:testing

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: bpdm-pool/Dockerfile
          push: true
          tags: kind-registry:5000/bpdm-pool:testing


      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: bpdm-bridge-dummy/Dockerfile
          push: true
          tags: kind-registry:5000/bpdm-bridge-dummy:testing


      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: bpdm-orchestrator/Dockerfile
          push: true
          tags: kind-registry:5000/bpdm-orchestrator:testing

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.3

      # Setup python as a prerequisite for chart linting
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # run chart linting
      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }} --config charts/config/chart-testing-config.yaml

      # install the chart to the kind cluster and run helm test
      # define charts to test with the --charts parameter
      - name: Run chart-testing (install)
        run: |
          ct install --charts charts/bpdm,charts/bpdm/charts/bpdm-pool,charts/bpdm/charts/bpdm-gate,charts/bpdm/charts/bpdm-bridge-dummy,charts/bpdm/charts/bpdm-cleaning-service-dummy,charts/bpdm/charts/bpdm-orchestrator --config charts/config/chart-testing-config.yaml
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'

      # Upgrade the released chart version with the locally available chart
      # default value for event_name != workflow_dispatch
      - name: Run helm upgrade
        run: |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
            helm install bpdm tractusx-dev/bpdm --version ${{ github.event.inputs.upgrade_from|| '3.1.2' }}
            helm dependency update charts/bpdm
            helm upgrade bpdm charts/bpdm
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'